# Generated by Django 3.2 on 2022-12-21 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Введите email', max_length=100, unique=True, verbose_name='Email'),
        ),
    ]
